services:
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - JWT_SECRET=inirahasiakitabersama
    depends_on:
      - db
    command: npx sequelize db:create && npx sequelize db:migrate && npm start
    expose:
      - 3000

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /data:/var/lib/postgresql/data