version: '3.9'

services:
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - JWT_SECRET=inirahasiakitabersama
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres